# Nom de l'application (doit correspondre au nom du fichier sur GitHub)
spring.application.name=user-service
server.port=8082

# On active le Config Server
spring.cloud.config.enabled=true

# LIEN VERS LE SERVEUR DE CONFIGURATION
spring.config.import=optional:configserver:http://localhost:8888

# On force l'adresse de Consul pour le d\u00E9veloppement local
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
