# ===============================================================
# IDENTITE DU MICROSERVICE
# ===============================================================
# Ce nom doit \u00EAtre identique au fichier .properties sur GitHub
spring.application.name=healthcare-ui

# Port sur lequel l'interface web sera accessible (http://localhost:8080)
server.port=8080

# ===============================================================
# CONFIGURATION DU CONFIG SERVER (Lien vers GitHub via Java)
# ===============================================================

# 1. On active la r\u00E9cup\u00E9ration de configuration distante
spring.cloud.config.enabled=true

# 2. IMPORT DE LA CONFIGURATION (Le point le plus important) :
# ---------------------------------------------------------------
# POUR TESTER DANS INTELLIJ (Windows) : Utilise localhost
spring.config.import=optional:configserver:http://localhost:8888

# POUR LE LANCEMENT FINAL DANS DOCKER : Il faudra commenter la ligne au-dessus 
# et d\u00E9commenter celle ci-dessous (le nom du service Docker) :
# spring.config.import=optional:configserver:http://config-server:8888
# ---------------------------------------------------------------

# Optionnel : Si le serveur de config n'est pas trouv\u00E9, le service attendra au lieu de crasher
spring.cloud.config.fail-fast=false

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500