spring.application.name=note-service
server.port=8083

# CONNEXION AU CONFIG SERVER (R\u00C9PAR\u00C9 POUR DOCKER)
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://config-server:8888

# CONNEXION CONSUL (R\u00C9PAR\u00C9 POUR DOCKER)
spring.cloud.consul.host=healthcare-consul
spring.cloud.consul.port=8500