spring.application.name=note-service
server.port=8083

# Connexion au Config Server
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888

# Force Consul en local pour le d\u00E9v
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500