# Nom de l'application (doit correspondre au nom du fichier sur GitHub)
spring.application.name=patient-service
server.port=8081

# On active le Config Server
spring.cloud.config.enabled=true

# LIEN VERS LE SERVEUR DE CONFIGURATION
# C'est ici que le service va aller chercher MySQL, Consul, etc.
spring.config.import=optional:configserver:http://config-server:8888