spring.application.name=patient-service
server.port=8081

# ON ACTIVE LE CONFIG SERVER
spring.cloud.config.enabled=true

# LIEN VERS LE SERVEUR DE CONFIGURATION (R\u00C9PAR\u00C9 POUR DOCKER)
spring.config.import=optional:configserver:http://config-server:8888

# ON PARAM\u00C8TRE L'ADRESSE DE CONSUL POUR DOCKER
spring.cloud.consul.host=healthcare-consul
spring.cloud.consul.port=8500