spring.application.name=config-server
server.port=8888

# R\u00C9PARATION DOCKER : On cherche Consul sur le nom du conteneur
spring.cloud.consul.host=healthcare-consul
spring.cloud.consul.port=8500

# CONFIGURATION GITHUB
spring.cloud.config.server.git.uri=https://github.com/Akh138/healthcare-config-repo.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.force-pull=true

# Healthcheck au Config Server pour que Docker sache qu'il est pr\u00EAt
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always